name: algorithms
description: 'Theoretical course "Algorithms in Python 3", Moscow Institute of Physics and Technology (MIPT).'
version: 0.0.0

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  test: ^1.21.4

dev_dependencies:

